# Generated by Django 2.1 on 2019-01-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('created_date',), 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipe'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='notest',
            new_name='notes',
        ),
    ]
